version: '2'
services:
  keycloak-db:
    image: postgres:11.5
    container_name: maxilog-keycloak-db
    volumes:
      - keycloak-datastore:/var/lib/postresql/data
    ports:
      - '25432:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak:7.0.0
    container_name: maxilog-keycloak
    ports:
      - '8180:8080'
    volumes:
      - ./realm:/opt/jboss/keycloak/realm-config
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/realm-config/realm.json
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
volumes:
  keycloak-datastore: